// Generated by grunt: browserify-imports
(function moduleInit_appnamemulticomponent() {
	'use strict';

	// Add require for other modules here
	// require('../my.other.module');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./idv-layout');
	require('./idv-accordion');
	require('./idv-nonphoto-birthcert');
	require('./idv-nonphoto-pension');
	require('./idv-primary-ageproof');
	require('./idv-primary-aulicence');
	require('./idv-primary-aupassport');
	require('./idv-primary-otherlicence');
	require('./idv-primary-otherpassport');
	require('./idv-secondary-govtcard');
	require('./idv-secondary-marriagecert');
	require('./idv-secondary-medicare');
	require('./idv-secondary-utilcard');
	require('./factories/idvFactory.js');


	var modules = ["appname.common.idv.idvLayout", "appname.common.idv.idvAccordion",
		"appname.common.idv.idvNonphotoBirthcert",
		"appname.common.idv.idvNonphotoPension",
		"appname.common.idv.idvPrimaryAgeproof",
		"appname.common.idv.idvPrimaryAulicence",
		"appname.common.idv.idvPrimaryAupassport",
		"appname.common.idv.idvPrimaryOtherlicence",
		"appname.common.idv.idvPrimaryOtherpassport",
		"appname.common.idv.idvSecondaryGovtcard",
		"appname.common.idv.idvSecondaryMarriagecert",
		"appname.common.idv.idvSecondaryMedicare",
		"appname.common.idv.idvSecondaryUtilcard",
		"appname.common.factories.idvFactory"
		];
	// EndRequire

	// Add your angular module dependencies here
	// modules.push('my.other.module');

	angular.module('appname.common.idv', modules);
})();
