// Generated by grunt: browserify-imports
(function moduleInit_appnameProject() {
	'use strict';

	// Add require for other modules here
	// require('../my.other.module');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./project-components');
	var modules = ["appname.project.projectComponents"];
	// EndRequire

	// Add your angular module dependencies here
	// modules.push('my.other.module');

	angular.module('appname.project', modules);
})();
